        <div className="risk-ring"><div className="risk-core"><ShieldCheck/><b>Low risk</b><span>No critical findings</span></div></div>
        <div className="mini-list"><div><CheckCircle2/><span>Identity enforcement</span><b>100%</b></div><div><CheckCircle2/><span>Audited interactions</span><b>100%</b></div><div><AlertTriangle/><span>Sync warnings</span><b>1</b></div></div>
      </div>
    </div>
    <div className="stats-grid">
      <Stat icon={Users} label="Active users" value={`${users.filter(u=>u.status==='Active').length} / ${users.length}`} delta="All licensed"/>
      <Stat icon={MessageSquareText} label="Questions this month" value="642" delta="+18% vs last month"/>
      <Stat icon={Plug} label="Connected tools" value={active} delta="Across 5 categories"/>
      <Stat icon={ZapOff} label="Policy blocks" value="3" delta="All blocked before data access" tone="warning"/>
    </div>
    <div className="two-col">
      <div className="panel"><div className="section-title"><div><span className="micro">LIVE ACTIVITY</span><h3>What BIQc is doing now</h3></div><button className="text-btn" onClick={()=>go('audit')}>View all <ArrowRight/></button></div>
        <ActivityFeed/>
      </div>
      <div className="panel"><div className="section-title"><div><span className="micro">CONNECTION HEALTH</span><h3>Business systems</h3></div><button className="text-btn" onClick={()=>go('connections')}>Manage <ArrowRight/></button></div>
        <div className="conn-stack">{connections.filter(c=>c.status==='Connected').slice(0,5).map(c=><div className="conn-row" key={c.id}><AppIcon c={c}/><div><b>{c.name}</b><span>{c.scope}</span></div><div className={`health-pill ${c.health==='Healthy'?'good':'warn'}`}>{c.health==='Healthy'?<Check/>:<AlertTriangle/>}{c.health}</div></div>)}</div>
      </div>
    </div>
    <div className="panel prompt-card"><div className="prompt-copy"><div className="ai-badge"><BrainCircuit/></div><div><span className="micro">TRY THE GOVERNED WORKFLOW</span><h3>Ask a question, see the policy and tool path.</h3><p>Demo evidence, permissions and confirmations in the same interaction.</p></div></div><button className="btn primary" onClick={()=>go('ask')}>Open Ask BIQc <ArrowRight/></button></div>
  </>
}

function Stat({icon:Icon,label,value,delta,tone}){return <div className="stat panel"><div className={`stat-icon ${tone||''}`}><Icon/></div><div><span>{label}</span><b>{value}</b><small>{delta}</small></div></div>}

function ActivityFeed(){const rows=[['JW','James asked','Which deals need attention this week?','HubSpot','12 sec'],['SC','Sarah asked','Which invoices are overdue by >30 days?','Xero','2 min'],['PD','Priya drafted','Supplier payment follow-up email','Gmail','6 min'],['TN','Tom was blocked','HR salary data · Contractor role','Policy','11 min']];return <div className="activity-feed">{rows.map((r,i)=><div className="activity-row" key={i}><div className={`avatar ${i===3?'blocked':''}`}>{r[0]}</div><div className="activity-copy"><div><b>{r[1]}</b><span>{r[4]}</span></div><p>{r[2]}</p><small>{r[3]}</small></div></div>)}</div>}

function Ask({connections,go,notify}){
  const [messages,setMessages]=useState([{type:'assistant',content:'Ask about your connected business systems. I’ll show what I used, what policy allowed, and any action that needs your confirmation.',meta:'Governed session · Sources enforced'}]);
  const [input,setInput]=useState(''); const [thinking,setThinking]=useState(false); const [model,setModel]=useState('GPT-5');
  const prompts=['Which invoices are overdue by more than 30 days?','Which deals need attention this week?','Draft a follow-up to Northbridge — don’t send it','What is everyone’s salary?'];
  const send=(text=input)=>{if(!text.trim())return; setMessages(m=>[...m,{type:'user',content:text}]);setInput('');setThinking(true);setTimeout(()=>{setThinking(false); if(text.toLowerCase().includes('salary')) setMessages(m=>[...m,{type:'blocked',content:'I can’t access HR & salary data for your current role. The request was stopped before any HR data was retrieved.',meta:'Policy: HR & salaries · Role: Admin demo override disabled'}]); else if(text.toLowerCase().includes('draft')) setMessages(m=>[...m,{type:'assistant',content:'I found the Northbridge opportunity in HubSpot and drafted a concise follow-up based on the last activity. I have not sent anything.',meta:'2 sources · HubSpot + Gmail',tool:true,action:true}]); else if(text.toLowerCase().includes('deal')) setMessages(m=>[...m,{type:'assistant',content:'Three deals need attention: Northbridge ($84k) has been idle 9 days, Coastline Health ($61k) has no next step, and Everfield ($42k) has a proposal expiring Friday.',meta:'Evidence: HubSpot · 18 records checked',tool:true}]); else setMessages(m=>[...m,{type:'assistant',content:'There are 7 invoices overdue by more than 30 days, totalling A$48,620. The two largest are INV-1048 (A$16,400, 46 days) and INV-1039 (A$11,250, 39 days).',meta:'Evidence: Xero · invoices read-only',tool:true}])},800)};
  return <div className="ask-layout">
    <div className="chat-main">
      <div className="chat-head"><div><div className="bot-icon"><Sparkles/></div><div><h2>Ask BIQc</h2><span><span className="live-dot"/>Governed session</span></div></div><div className="chat-head-actions"><button className="btn secondary compact" onClick={()=>setMessages(messages.slice(0,1))}>New chat</button><button className="icon-btn" onClick={()=>notify('Conversation menu opened in demo')}><MoreHorizontal/></button></div></div>
      <div className="chat-scroll">
        <div className="chat-date">TODAY · NORTHSTAR OPS</div>
        {messages.map((m,i)=><Message m={m} key={i} notify={notify}/>) }
        {thinking&&<div className="message assistant"><div className="msg-avatar"><Bot/></div><div className="msg-body"><div className="thinking"><i/><i/><i/> Checking permissions and sources…</div></div></div>}
      </div>
      <div className="composer-wrap"><div className="prompt-chips">{prompts.map(p=><button key={p} onClick={()=>send(p)}>{p}</button>)}</div><div className="composer"><button className="icon-btn" onClick={()=>notify('Attachment picker opened in demo')}><PlusIcon/></button><textarea rows="1" placeholder="Ask anything about your business…" value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}}/><button className="model-select" onClick={()=>setModel(m=>m==='GPT-5'?'Claude 4':'GPT-5')}>{model}<ChevronDown/></button><button className="send-btn" onClick={()=>send()}><Send/></button></div><div className="composer-foot"><ShieldCheck/> Permissions are checked before BIQc sees business data. <span>Enter to send · Shift+Enter for new line</span></div></div>
    </div>
    <aside className="context-panel"><div className="context-head"><span className="micro">SESSION CONTEXT</span><button className="icon-btn ghost" onClick={()=>notify('Session context controls opened')}><SlidersHorizontal/></button></div><h3>What BIQc can use</h3><p className="muted">Access is scoped to you and this workspace.</p>
      <div className="context-section"><label>Connected sources</label>{connections.filter(c=>c.status==='Connected').map(c=><div className="source-row" key={c.id}><AppIcon c={c} small/><span>{c.name}</span><CheckCircle2/></div>)}</div>
      <div className="context-section"><label>Always-on controls</label><Guard label="Role permissions"/><Guard label="Prompt audit"/><Guard label="Workspace isolation"/><Guard label="No shared training"/></div>
      <button className="btn secondary full" onClick={()=>go('rules')}><Shield/>View my permissions</button>
    </aside>
  </div>
}

function Message({m,notify}){const [confirmed,setConfirmed]=useState(false);return <div className={`message ${m.type}`}><div className="msg-avatar">{m.type==='user'?'SC':m.type==='blocked'?<LockKeyhole/>:<Bot/>}</div><div className="msg-body"><div className="msg-top"><b>{m.type==='user'?'You':m.type==='blocked'?'BIQc policy':'BIQc'}</b>{m.meta&&<span>{m.meta}</span>}</div><p>{m.content}</p>{m.tool&&<div className="tool-trace"><div className="trace-step"><div className="trace-icon"><ShieldCheck/></div><div><b>Permission check passed</b><span>Your role can access the requested business data.</span></div><CheckCircle2/></div><div className="trace-step"><div className="trace-icon"><Plug/></div><div><b>Connected source queried</b><span>Minimum required scope · read-only</span></div><CheckCircle2/></div>{m.action&&<div className="draft-action"><div><div className="app-mini">G</div><div><b>Draft email to Northbridge</b><span>“Hi Alex, following up on…”</span></div></div>{confirmed?<span className="confirmed"><CheckCheck/> Sent in demo</span>:<div><button className="btn secondary compact" onClick={()=>notify('Draft preview opened')}>Review</button><button className="btn primary compact" onClick={()=>{setConfirmed(true);notify('Action confirmed and logged')}}>Confirm & send</button></div>}</div>}</div>}</div></div>}

function Pulse({go,notify}){return <><PageHead eyebrow="Cross-system intelligence" title="Pulse" desc="Signals that deserve attention, prioritised across your connected tools." actions={<button className="btn secondary" onClick={()=>notify('Pulse refreshed with latest permitted signals')}><RefreshCw/>Refresh signals</button>}/><div className="pulse-grid"><Signal severity="high" icon={CircleDollarSign} label="Cash" title="A$48.6k overdue beyond 30 days" body="7 invoices · two accounts represent 57% of overdue value" source="Xero" action="Review invoices"/><Signal severity="medium" icon={BarChart3} label="Pipeline" title="A$187k pipeline has stalled" body="3 opportunities have no activity or next step in the last 7 days" source="HubSpot" action="Open deals"/><Signal severity="low" icon={CalendarDays} label="Capacity" title="Thursday has a delivery gap" body="2 field jobs overlap with only one qualified team available" source="Calendar + ServiceM8" action="See schedule"/></div><div className="two-col"><div className="panel"><div className="section-title"><div><span className="micro">WHY THIS MATTERS</span><h3>Evidence, not dashboards</h3></div></div><div className="insight-block"><BrainCircuit/><div><b>BIQc connects the dots before you ask.</b><p>Pulse watches permitted signals across systems and explains why an item is worth your attention. It never expands a user’s data access to produce a signal.</p><button className="text-btn" onClick={()=>go('architecture')}>See how governance is applied <ArrowRight/></button></div></div></div><div className="panel"><div className="section-title"><div><span className="micro">SCHEDULED BRIEF</span><h3>Monday owner brief</h3></div><span className="preview-tag">PROTOTYPE</span></div><div className="brief-preview"><div className="brief-time"><Clock3/><div><b>Every Monday · 7:30 AM</b><span>Australia/Melbourne</span></div></div><div className="brief-tags"><span>Cash</span><span>Pipeline</span><span>Capacity</span><span>Exceptions</span></div><button className="btn secondary full" onClick={()=>notify('Scheduled brief settings opened')}>Configure brief</button></div></div></div></>}
