function Signal({severity,icon:Icon,label,title,body,source,action}){return <div className={`signal-card panel ${severity}`}><div className="signal-top"><div className="signal-icon"><Icon/></div><span>{label}</span><i>{severity==='high'?'Needs attention':severity==='medium'?'Watch':'FYI'}</i></div><h3>{title}</h3><p>{body}</p><div className="signal-foot"><span><Database/>{source}</span><button className="text-btn" onClick={()=>document.dispatchEvent(new CustomEvent('biqc-demo-action',{detail:action}))}>{action}<ArrowRight/></button></div></div>}

function Connections({connections,setConnections,setModal,notify}){
  const [filter,setFilter]=useState('All'); const [search,setSearch]=useState('');
  const shown=connections.filter(c=>(filter==='All'||c.category===filter||filter==='Connected'&&c.status==='Connected')&&c.name.toLowerCase().includes(search.toLowerCase()));
  const disconnect=(c)=>{setConnections(cs=>cs.map(x=>x.id===c.id?{...x,status:'Available',health:'—',sync:'Never'}:x));notify(`${c.name} disconnected and access revoked`)};
  const connect=(c)=>setModal({type:'connect',connection:c});
  return <><PageHead eyebrow="Company connections" title="Connect once. Govern everywhere." desc="Approve scopes at workspace level, then control what each person can use." actions={<button className="btn primary" onClick={()=>setModal({type:'catalogue'})}><Plug/>Add connection</button>}/>
    <div className="metric-strip panel"><div><span>Connected</span><b>{connections.filter(c=>c.status==='Connected').length}</b></div><div><span>Healthy</span><b>{connections.filter(c=>c.health==='Healthy').length}</b></div><div><span>Sync warning</span><b className="warn-text">1</b></div><div><span>Last successful sync</span><b>1 min ago</b></div></div>
    <div className="toolbar"><div className="search-box"><Search/><input placeholder="Search connections" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="filter-tabs">{['All','Connected','CRM','Accounting','Email','Calendar'].map(f=><button className={filter===f?'active':''} onClick={()=>setFilter(f)} key={f}>{f}</button>)}</div></div>
    <div className="connection-grid">{shown.map(c=><div className="connection-card panel" key={c.id}><div className="connection-top"><AppIcon c={c}/><button className="icon-btn ghost" onClick={()=>notify(`${c.name} menu opened`)}><MoreHorizontal/></button></div><div><h3>{c.name}</h3><span className="category">{c.category}</span></div><div className="scope-box"><span>Approved scope</span><p>{c.scope}</p></div>{c.status==='Connected'?<><div className="conn-status"><span className={c.health==='Healthy'?'healthy':'warning'}>{c.health==='Healthy'?<CheckCircle2/>:<AlertTriangle/>}{c.health}</span><small>Synced {c.sync}</small></div><div className="card-actions"><button className="btn secondary" onClick={()=>setModal({type:'manage',connection:c})}>Manage</button><button className="btn danger-ghost" onClick={()=>disconnect(c)}>Disconnect</button></div></>:<button className="btn primary full" onClick={()=>connect(c)}>Connect {c.name}</button>}</div>)}</div>
  </>
}

function Plugins({notify}){const [plugins,setPlugins]=useState([
 {name:'CRM Research',desc:'Search accounts, deals and recent activity',tools:['HubSpot search','Deal read'],on:true,icon:FileSearch},
 {name:'Email Assistant',desc:'Draft, review and send email with confirmation',tools:['Gmail read','Gmail draft','Gmail send'],on:true,icon:Mail},
 {name:'Finance Analyst',desc:'Read accounting data and explain cash movement',tools:['Xero reports','Invoice read'],on:true,icon:CircleDollarSign},
 {name:'Meeting Coordinator',desc:'Find availability and propose meeting times',tools:['Calendar read','Availability'],on:true,icon:CalendarDays},
 {name:'Workflow Runner',desc:'Launch approved Zapier automations',tools:['Zapier action'],on:false,icon:Workflow},
 ]);const toggle=i=>{setPlugins(p=>p.map((x,n)=>n===i?{...x,on:!x.on}:x));notify('Plugin policy updated')};return <><PageHead eyebrow="Tool layer" title="Plugins & actions" desc="Expose useful capabilities to Ask BIQc without exposing the underlying integration complexity." actions={<button className="btn primary" onClick={()=>notify('Plugin builder opened in demo')}><PlusIcon/>Create plugin</button>}/><div className="notice"><ShieldCheck/><div><b>Actions inherit user permissions.</b><span>A plugin cannot bypass role rules or connected-system scopes.</span></div></div><div className="plugin-grid">{plugins.map((p,i)=>{const Icon=p.icon;return <div className={`plugin-card panel ${p.on?'':'disabled'}`} key={p.name}><div className="plugin-top"><div className="plugin-icon"><Icon/></div><Toggle checked={p.on} onChange={()=>toggle(i)}/></div><h3>{p.name}</h3><p>{p.desc}</p><div className="tool-tags">{p.tools.map(t=><span key={t}><TerminalSquare/>{t}</span>)}</div><div className="plugin-foot"><span className={p.on?'active-state':'off-state'}>{p.on?<CheckCircle2/>:<ZapOff/>}{p.on?'Available in Ask BIQc':'Disabled'}</span><button className="text-btn" onClick={()=>notify(`${p.name} configuration opened`)}>Configure <ChevronRight/></button></div></div>})}</div></>}

function Team({users,setUsers,setModal,notify}){const revoke=(u)=>{setUsers(us=>us.map(x=>x.id===u.id?{...x,status:x.status==='Active'?'Revoked':'Active'}:x));notify(u.status==='Active'?`${u.name}'s access revoked immediately`:`${u.name} reactivated`)};return <><PageHead eyebrow="Identity & access" title="Team access" desc="Roles follow the person. Revoke a user and their AI access ends immediately." actions={<button className="btn primary" onClick={()=>setModal({type:'invite'})}><Users/>Invite member</button>}/><div className="stats-grid compact-stats"><Stat icon={Users} label="Licensed seats" value="4 / 9" delta="5 seats available"/><Stat icon={ShieldCheck} label="Active members" value={users.filter(u=>u.status==='Active').length} delta="1 admin · 3 team"/><Stat icon={UserX} label="Revoked this month" value={users.filter(u=>u.status==='Revoked').length} delta="Access ends instantly"/><Stat icon={Fingerprint} label="MFA coverage" value="100%" delta="All active users"/></div><div className="table-panel panel"><div className="table-toolbar"><div className="search-box"><Search/><input placeholder="Search people"/></div><button className="btn secondary" onClick={()=>notify('Team filters opened in demo')}><Filter/>Filter</button></div><table><thead><tr><th>Person</th><th>Role</th><th>Status</th><th>Last active</th><th>Prompts</th><th></th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td><div className="person"><div className="avatar">{u.initials}</div><div><b>{u.name}</b><span>{u.email}</span></div></div></td><td><button className="role-chip" onClick={()=>setModal({type:'role',user:u})}>{u.role}<ChevronDown/></button></td><td><span className={`status-badge ${u.status.toLowerCase()}`}><i/>{u.status}</span></td><td>{u.last}</td><td>{u.prompts}</td><td><button className={u.status==='Active'?'btn danger-ghost compact':'btn secondary compact'} onClick={()=>revoke(u)}>{u.status==='Active'?'Revoke':'Reactivate'}</button></td></tr>)}</tbody></table></div></>}

function Rules({roles,setRoles,notify}){const areas=['Financials','Client personal data','HR & salaries','Pipeline & deals','Email','Calendar'];const toggle=(role,area)=>{if(role==='Admin'){notify('Admin baseline cannot be reduced in this demo','warning');return}setRoles(r=>({...r,[role]:{...r[role],[area]:!r[role][area]}}));notify(`${role} permissions updated`)};return <><PageHead eyebrow="Policy engine" title="Roles & data rules" desc="Data boundaries follow the role and are enforced before prompts, retrieval and tool execution." actions={<button className="btn secondary" onClick={()=>notify('Policy change log opened in demo')}><FileSearch/>Policy change log</button>}/><div className="notice orange"><LockKeyhole/><div><b>Policy-first retrieval</b><span>Blocked data is never retrieved into model context — it is not merely hidden from the final answer.</span></div></div><div className="matrix panel"><div className="matrix-head"><div><span className="micro">DATA BOUNDARIES</span><h3>Role permissions</h3></div><span className="preview-tag">INTERACTIVE DEMO</span></div><table><thead><tr><th>Data area</th>{Object.keys(roles).map(r=><th key={r}>{r}<span>{r==='Admin'?'Full control':r==='Sales'?'Customer-facing':r==='Finance'?'Financial ops':'Limited access'}</span></th>)}</tr></thead><tbody>{areas.map(a=><tr key={a}><td><div className="area-cell"><DataIcon area={a}/><div><b>{a}</b><span>{areaDesc(a)}</span></div></div></td>{Object.keys(roles).map(r=><td key={r}><Toggle checked={roles[r][a]} onChange={()=>toggle(r,a)} locked={r==='Admin'}/></td>)}</tr>)}</tbody></table></div><div className="two-col"><div className="panel"><div className="section-title"><div><span className="micro">ALWAYS ON</span><h3>Non-negotiable guardrails</h3></div></div><div className="guard-list"><Guard label="Business-only AI use" sub="AI use stays inside the governed workspace"/><Guard label="Workspace separation" sub="Each user’s memory is scoped to their account"/><Guard label="Prompt audit trail" sub="Every AI interaction is recorded per user"/><Guard label="Training restriction" sub="Business prompts are not added to shared training datasets"/></div></div><div className="panel"><div className="section-title"><div><span className="micro">POLICY TESTER</span><h3>Preview a user request</h3></div></div><PolicyTester roles={roles}/></div></div></>}

function PolicyTester({roles}){const [role,setRole]=useState('Sales');const [prompt,setPrompt]=useState("Show me everyone's salary");const blocked=prompt.toLowerCase().includes('salary')&&!roles[role]['HR & salaries'];return <div className="tester"><div className="form-row"><label>Act as role<select value={role} onChange={e=>setRole(e.target.value)}>{Object.keys(roles).map(r=><option key={r}>{r}</option>)}</select></label></div><label>Prompt<textarea value={prompt} onChange={e=>setPrompt(e.target.value)}/></label><div className={`test-result ${blocked?'blocked':'allowed'}`}>{blocked?<LockKeyhole/>:<CheckCircle2/>}<div><b>{blocked?'Blocked before retrieval':'Allowed'}</b><span>{blocked?'HR & salaries is outside this role’s data boundary.':'This role can access the requested data area.'}</span></div></div></div>}
