        {section==='Data retention'&&<SettingsList eyebrow="DATA RETENTION" title="Retention controls" desc="Prototype controls for governed history and operational logs." items={[["Prompt audit history","365 days"],["Connector sync cache","90 days"],["Revoked user sessions","Terminate immediately"]]} notify={notify}/>} 
        {section==='Billing & wallet'&&<><Wallet usage={usage} setUsage={setUsage}/><SettingsList eyebrow="SEAT LICENSING" title="Workspace seats" desc="Demo commercial controls for the workspace." items={[["Licensed seats","4 / 9"],["Admin governance seat","Included"],["Wallet auto top-up","Off"]]} notify={notify}/></>}
        {section==='API & webhooks'&&<SettingsList eyebrow="DEVELOPER" title="API & webhooks" desc="Operational endpoints for governed extensions and event delivery." items={[["Workspace API key","••••••••BQ7K"],["Webhook signing secret","Configured"],["Audit event webhook","Enabled"],["Retry policy","Exponential backoff"]]} notify={notify}/>} 
      </div></div></>
}

function Wallet({usage,setUsage}){return <div className="settings-section"><div><span className="micro">AI WALLET</span><h3>Usage controls</h3><p>Prototype control for budget visibility and safe limits.</p></div><div className="wallet-card"><div><span>September usage</span><b>A$ {usage}.20</b><small>of A$100 monthly guardrail</small></div><div className="usage-bar"><i style={{width:`${usage}%`}}/></div><label className="range-label">Demo usage<input type="range" min="5" max="95" value={usage} onChange={e=>setUsage(e.target.value)}/></label></div></div>}
function SettingsList({eyebrow,title,desc,items,notify}){return <div className="settings-section"><div><span className="micro">{eyebrow}</span><h3>{title}</h3><p>{desc}</p></div><div className="settings-list">{items.map(([k,v])=><div key={k}><span>{k}</span><b>{v}</b></div>)}</div><button className="btn primary" onClick={()=>notify(`${title} saved in demo`)}>Save changes</button></div>}

function CommandPalette({go,close}){const [q,setQ]=useState('');const flat=navGroups.flatMap(g=>g.items).filter(i=>i[1].toLowerCase().includes(q.toLowerCase()));return <div className="overlay" onMouseDown={close}><div className="command-modal" onMouseDown={e=>e.stopPropagation()}><div className="command-input"><Search/><input autoFocus placeholder="Search pages and actions…" value={q} onChange={e=>setQ(e.target.value)}/><kbd>ESC</kbd></div><div className="command-results"><span className="micro">NAVIGATE</span>{flat.map(([id,label,Icon])=><button key={id} onClick={()=>go(id)}><Icon/><span>{label}</span><kbd>↵</kbd></button>)}</div><div className="command-foot">Tip: try “connections”, “audit”, or “architecture”</div></div></div>}

function Modal({modal,close,ctx}){const {setConnections,notify,setUsers}=ctx;if(modal.type==='connect'){const c=modal.connection;const connect=()=>{setConnections(cs=>cs.map(x=>x.id===c.id?{...x,status:'Connected',health:'Healthy',sync:'Just now'}:x));notify(`${c.name} connected with approved scopes`);close()};return <ModalShell close={close} title={`Connect ${c.name}`} icon={<AppIcon c={c}/>}><div className="oauth-flow"><div className="oauth-step done"><span>1</span><div><b>Authenticate with {c.name}</b><small>Your password stays with {c.name}.</small></div><Check/></div><div className="oauth-step current"><span>2</span><div><b>Approve requested scope</b><small>{c.scope}</small></div></div><div className="scope-perms"><label><CheckCircle2/>Read business records</label><label><CheckCircle2/>Sync permitted metadata</label><label><LockKeyhole/>Actions require role permission</label></div><div className="modal-actions"><button className="btn secondary" onClick={close}>Cancel</button><button className="btn primary" onClick={connect}>Approve & connect</button></div></div></ModalShell>}
 if(modal.type==='invite') return <InviteContent close={close} notify={notify} setUsers={setUsers}/>
 if(modal.type==='role'){const u=modal.user;return <ModalShell close={close} title={`Change ${u.name}'s role`} icon={<Shield/>}><div className="role-options">{['Admin','Sales','Finance','Contractor'].map(r=><button className={u.role===r?'selected':''} onClick={()=>{setUsers(us=>us.map(x=>x.id===u.id?{...x,role:r}:x));notify(`${u.name} is now ${r}`);close()}} key={r}><div><b>{r}</b><span>{r==='Admin'?'Full workspace control':r==='Sales'?'CRM, client data and email':r==='Finance'?'Accounting and financial operations':'Restricted external access'}</span></div>{u.role===r&&<CheckCircle2/>}</button>)}</div></ModalShell>}
 if(modal.type==='manage'){const c=modal.connection;return <ModalShell close={close} title={`${c.name} connection`} icon={<AppIcon c={c}/>}><div className="manage-conn"><div className="manage-row"><span>Status</span><b className="healthy-text"><CheckCircle2/>Connected</b></div><div className="manage-row"><span>Approved scope</span><b>{c.scope}</b></div><div className="manage-row"><span>Last sync</span><b>{c.sync}</b></div><div className="manage-row"><span>Token storage</span><b>Encrypted credential vault</b></div><button className="btn secondary full" onClick={()=>{notify(`${c.name} OAuth token refreshed`);close()}}><RefreshCw/>Reconnect OAuth</button></div></ModalShell>}
 return <ModalShell close={close} title="Connection catalogue" icon={<Plug/>}><div className="catalogue"><p>Search the supported business systems and connect them with workspace-approved scopes.</p><div className="catalogue-grid">{initialConnections.slice(0,6).map(c=><div key={c.id}><AppIcon c={c}/><span>{c.name}</span></div>)}</div><button className="btn primary full" onClick={close}>Browse all connectors</button></div></ModalShell>}

function InviteContent({close,notify,setUsers}){const [name,setName]=useState('Alex Morgan');const [email,setEmail]=useState('alex@northstar.au');const [role,setRole]=useState('Sales');const invite=()=>{setUsers(us=>[...us,{id:Date.now(),name,initials:name.split(' ').map(x=>x[0]).join('').slice(0,2),email,role,status:'Active',last:'Invited',prompts:0}]);notify('Invitation created in demo');close()};return <ModalShell close={close} title="Invite member" icon={<Users/>}><div className="modal-form"><label>Name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Email<input value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Role<select value={role} onChange={e=>setRole(e.target.value)}><option>Sales</option><option>Finance</option><option>Contractor</option><option>Admin</option></select></label><div className="invite-note"><ShieldCheck/>This role’s data rules will apply from the first session.</div><div className="modal-actions"><button className="btn secondary" onClick={close}>Cancel</button><button className="btn primary" onClick={invite}>Send invite</button></div></div></ModalShell>}

function ModalShell({close,title,icon,children}){return <div className="overlay" onMouseDown={close}><div className="modal-card" onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div className="modal-title-icon">{icon}</div><div><span className="micro">BIQc GOVERNED FLOW</span><h2>{title}</h2></div><button className="icon-btn ghost ml-auto" onClick={close}><X/></button></div>{children}</div></div>}

function AppIcon({c,small}) {return <div className={`app-icon ${small?'small':''}`} style={{'--app':c.color}}>{c.icon}</div>}
function Guard({label,sub}){return <div className="guard"><div className="locked-toggle"><LockKeyhole/><i/></div><div><b>{label}</b>{sub&&<span>{sub}</span>}</div></div>}
function Toggle({checked,onChange,locked}){return <button onClick={onChange} className={`toggle ${checked?'on':''} ${locked?'locked':''}`}><i/>{locked&&<LockKeyhole/>}</button>}
function DataIcon({area}){const M={'Financials':CircleDollarSign,'Client personal data':Users,'HR & salaries':KeyRound,'Pipeline & deals':BarChart3,'Email':Mail,'Calendar':CalendarDays};const I=M[area]||Database;return <div className="data-icon"><I/></div>}
function areaDesc(a){return ({Financials:'Xero · invoices · payroll totals','Client personal data':'Contacts · phone · email','HR & salaries':'Contracts · reviews · pay','Pipeline & deals':'CRM · deals · activity',Email:'Read · draft · send',Calendar:'Events · availability'})[a]}
function ResultBadge({result}){const cls=result==='Blocked'?'blocked':result==='Confirmed'||result==='Success'?'confirmed':'allowed';return <span className={`result-badge ${cls}`}>{result}</span>}
function BellIcon(){return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9"/><path d="M13.73 21a2 2 0 0 1-3.46 0"/></svg>}
function PlusIcon(){return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M12 5v14M5 12h14"/></svg>}

createRoot(document.getElementById('root')).render(<App/>);
